CREATE TABLE PAWNS
   (	CODE NUMBER NOT NULL ENABLE, 
	CODE_OF_CATEGORY NUMBER NOT NULL ENABLE, 
	CODE_OF_CLIENT VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	DESCRIPTION VARCHAR2(100 BYTE), 
	AMOUNT NUMBER(*,0) NOT NULL ENABLE, 
	COMMISSION_FEES NUMBER(*,0) NOT NULL ENABLE, 
	DATE_OF_DELIVERY DATE, 
	DATE_OF_RETURN DATE, 
	 CONSTRAINT "PAWNS_PK" PRIMARY KEY (CODE, CODE_OF_CLIENT, CODE_OF_CATEGORY)

CREATE TABLE CLIENTS
   (	CLIENT_NUMBER VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	SURNAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	NAME VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	PATRONYMIC VARCHAR2(20 BYTE), 
	PASSPORT_NUMBER VARCHAR2(6 BYTE), 
	PASSPORT_SERIES VARCHAR2(4 BYTE), 
	COMMENTARY" VARCHAR2(100 BYTE), 
	 CONSTRAINT "CLIENT_PK" PRIMARY KEY (CLIENT_NUMBER)

CREATE TABLE CATEGORIES_OF_PAWNS
   (	CATEGORY_NUMBER NUMBER NOT NULL ENABLE, 
	TITLE VARCHAR2(100 BYTE), 
	NOTE VARCHAR2(100 BYTE), 
	 PRIMARY KEY (CATEGORY_NUMBER)